name: CI Testing

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ubuntu:  # another top-level job key
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [Debug, Release, Dist]   # all configurations to build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git pkg-config cmake ninja-build gnome-desktop-testing \
            libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev \
            libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev \
            libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev \
            libdbus-1-dev libibus-1.0-dev libudev-dev

      - name: Set default gcc and g++ versions to latest
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Build
        env:
          CC: gcc
          CXX: g++
        run: |
          cmake -S . -B build
          cmake --build build --config=${{ matrix.config }}
        shell: bash



  windows:  # top-level job key
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release, Dist]   # all configurations to build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build --config=${{ matrix.config }}
        shell: pwsh


